const {
  default: ForgotPassword,
} = require('../Screen/prevAuth/Login/ForgotPassword');

exports.ImagerHanlde = {
  clientLogoSVG: require('../../assets/images/clientLogoSVG.svg'),
  clientLogo: require('../../assets/images/clientLogo.png'),
  logo: require('../../assets/images/crmLogo.png'),
  BottomNav: {
    menu: require('../../assets/images/menu.png'),
    home: require('../../assets/images/home.png'),
    add_user: require('../../assets/images/add_user.png'),
    bar_chart: require('../../assets/images/bar-chart.png'),
    Followup: require('../../assets/images/Followup.png'),
    imported_lead: require('../../assets/images/imported_lead.png'),
    leadGeneration: require('../../assets/images/lead-generation.png'),
    notification: require('../../assets/images/notification.png'),
  },
  noImage: require('../../assets/images/no-image.jpg'),
  AddIcon: require('../../assets/images/AddIcon.png'),
  listIcon: require('../../assets/images/list.png'),
  downArrow: require('../../assets/images/down-arrow.png'),
  backIcon: require('../../assets/images/back-icon.png'),
  infoIcon: require('../../assets/images/infoIcon.png'),
  caret_down: require('../../assets/images/caret-down.png'),
  whatsappIcon: require('../../assets/images/whatsappIcon.png'),
  MailIcon: require('../../assets/images/mail-open-outline.png'),
  checkmark: require('../../assets/images/checkmark-outline.png'),
  alarm: require('../../assets/images/alarm.png'),
  location: require('../../assets/images/location.png'),
  currentLocation: require('../../assets/images/currentLocation.png'),
  deleteIcon: require('../../assets/images/deleteIcon.png'),
  fileUpload: require('../../assets/images/fileUpload.png'),
  filterIcon: require('../../assets/images/filterIcon.png'),
  lock_closed: require('../../assets/images/lock-closed.png'),
  topArrow: require('../../assets/images/topArrow.png'),
  arrow_down: require('../../assets/images/arrow_down.png'),
  dollar_symbol: require('../../assets/images/dollar_symbol.png'),
  agentIcon: require('../../assets/images/agentIcon.png'),
  meeting_icon: require('../../assets/images/meeting_icon.png'),
  scheduleIcon: require('../../assets/images/scheduleIcon.png'),
  ReScheduleIcon: require('../../assets/images/ReScheduleIcon.png'),
  meetingIcon: require('../../assets/images/meetingIcon.png'),
  saleIcon: require('../../assets/images/saleIcon.png'),
  upSaleIcon: require('../../assets/images/upSaleIcon.png'),
  downSaleIcon: require('../../assets/images/downSaleIcon.png'),
  building_icon: require('../../assets/images/building_icon.png'),
  eye_outline: require('../../assets/images/eye-outline.png'),
  eye_off_outline: require('../../assets/images/eye-off-outline.png'),

  MenuNav: {
    exit: require('../../assets/images/exit-outline.png'),
    settings: require('../../assets/images/settings.png'),
    call: require('../../assets/images/call.png'),
    layers: require('../../assets/images/layers.png'),
    clients: require('../../assets/images/clients.png'),
  },
  CallIcon: {
    incoming: require('../../assets/images/incoming.png'),
    incoming_focused: require('../../assets/images/incoming-focused.png'),
    missed: require('../../assets/images/missed.png'),
    missed_focused: require('../../assets/images/missed-focused.png'),
    outgoing: require('../../assets/images/outgoing.png'),
    outgoing_focused: require('../../assets/images/outgoing-focused.png'),
    rejected: require('../../assets/images/rejected.png'),
    rejected_focused: require('../../assets/images/rejected-focused.png'),
    sim1_icon: require('../../assets/images/sim1_icon.png'),
    sim2_icon: require('../../assets/images/sim2_icon.png'),
    noSim_icon: require('../../assets/images/no-sim.png'),
  },
  setting: {
    company_details: require('../../assets/images/company_details.png'),
    department_icon: require('../../assets/images/department_icon.png'),
    crm_icon: require('../../assets/images/crm_icon.png'),
    subscription_icon: require('../../assets/images/subscription_icon.png'),
    logout_image: require('../../assets/images/logout_image.png'),
  },
  ForgotPassword: {
    forgotIcon: require('../../assets/images/forgotIcon.png'),
  },
  EditIcon: require('../../assets/images/edit_icon.png'),
  search: require('../../assets/images/search.png'),
  close: require('../../assets/images/close.png'),
  chatbox: require('../../assets/images/chatbox.png'),
  plusIcon: require('../../assets/images/plusIcon.png'),
  WebIcon: require('../../assets/images/WebIcon.png'),
  person_f: require('../../assets/images/person-f.png'),
  profile: {
    person: require('../../assets/images/person.png'),
    mail: require('../../assets/images/mail.png'),
    edit: require('../../assets/images/edit.png'),
    avatar: require('../../assets/images/avatar.png'),
  },
};
